// This file has been generated by Specta. DO NOT EDIT.

export type CopyRequest = { from: string[]; to: string; includes_hidden: boolean; strategy: CopyStrategy | null; includes_wrapping_dir: boolean }

export type ListDirOut = { path: string; short_path: string; children: DirItem[] }

export type CopyUiState = { left: DirActionPanel; right: DirActionPanel }

export type CopyStrategy = "BreathFirst" | "DepthFirst"

export type TauRpcFileActionInputTypes = { proc_name: "copy"; input_type: { __taurpc_type: CopyRequest } } | { proc_name: "moves"; input_type: { __taurpc_type: CopyRequest } }

export type TauRpcApiInputTypes = { proc_name: "hello_world"; input_type: null }

export type TauRpcActionRootOutputTypes = never

export type DirActionPanel = { root_path: string; current_pointer_path: string; show_hidden: boolean; items: DirItem[]; expanded_paths: string[]; selected_items: string[] }

export type TauRpcFileActionOutputTypes = { proc_name: "copy"; output_type: null } | { proc_name: "moves"; output_type: null }

export type TauRpcUIActionInputTypes = { proc_name: "list_dir"; input_type: { __taurpc_type: ListDirRequest } } | { proc_name: "toggle_expand"; input_type: { __taurpc_type: ToggleExpandRequest } } | { proc_name: "toggle_hidden"; input_type: { __taurpc_type: ToggleHiddenRequest } } | { proc_name: "update_cursor_path"; input_type: { __taurpc_type: UpdatePathRequest } } | { proc_name: "forward"; input_type: { __taurpc_type: UpdatePathRequest } } | { proc_name: "back"; input_type: { __taurpc_type: Side } } | { proc_name: "select"; input_type: { __taurpc_type: SelectRequest } } | { proc_name: "swap_sides"; input_type: null }

export type SelectRequest = { side: Side; path: string; selected: boolean }

export type TauRpcActionRootInputTypes = never

export type ToggleExpandRequest = { side: Side; folder_path: string; expanded: boolean }

export type Side = "left" | "right"

export type DirItem = { path: string; short_path: string; is_folder: boolean; permissions: DirPermission | null }

export type TauRpcDataInputTypes = { proc_name: "get_state"; input_type: null }

export type UpdatePathRequest = { side: Side; to: string }

export type TauRpcApiOutputTypes = { proc_name: "hello_world"; output_type: null }

export type DirPermission = { readable: boolean; writable: boolean; executable: boolean }

export type TauRpcUIActionOutputTypes = { proc_name: "list_dir"; output_type: DirItem[] } | { proc_name: "toggle_expand"; output_type: CopyUiState } | { proc_name: "toggle_hidden"; output_type: CopyUiState } | { proc_name: "update_cursor_path"; output_type: CopyUiState } | { proc_name: "forward"; output_type: CopyUiState } | { proc_name: "back"; output_type: CopyUiState } | { proc_name: "select"; output_type: CopyUiState } | { proc_name: "swap_sides"; output_type: CopyUiState }

export type TauRpcDataOutputTypes = { proc_name: "get_state"; output_type: CopyUiState }

export type ListDirRequest = { path: string; show_hidden: boolean; side: Side }

export type AppErrorIpc = { kind: string; message: string }

export type ToggleHiddenRequest = { side: Side; to: boolean }

const ARGS_MAP = {"actions.file":"{\"moves\":[\"params\"],\"copy\":[\"params\"]}","data":"{\"get_state\":[]}","":"{\"hello_world\":[]}","actions":"{}","actions.ui":"{\"toggle_hidden\":[\"params\"],\"toggle_expand\":[\"params\"],\"back\":[\"params\"],\"select\":[\"params\"],\"list_dir\":[\"params\"],\"forward\":[\"params\"],\"swap_sides\":[],\"update_cursor_path\":[\"params\"]}"}
import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
	'': [TauRpcApiInputTypes, TauRpcApiOutputTypes],
	'data': [TauRpcDataInputTypes, TauRpcDataOutputTypes],
	'actions': [TauRpcActionRootInputTypes, TauRpcActionRootOutputTypes],
	'actions.ui': [TauRpcUIActionInputTypes, TauRpcUIActionOutputTypes],
	'actions.file': [TauRpcFileActionInputTypes, TauRpcFileActionOutputTypes],
}